//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN_Helpers.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DATN_Helpers.ResourceFiles.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch chiếu bị trùng.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opt Sai.
        /// </summary>
        internal static string _107 {
            get {
                return ResourceManager.GetString("-107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("-108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tìm kiếm không hợp lệ .
        /// </summary>
        internal static string _1700 {
            get {
                return ResourceManager.GetString("-1700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu tìm kiếm.
        /// </summary>
        internal static string _1720 {
            get {
                return ResourceManager.GetString("-1720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percentage không hơp lệ (chỉ thuộc khoảng từ 1 - 100).
        /// </summary>
        internal static string _1800 {
            get {
                return ResourceManager.GetString("-1800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership không tồn tại hoặc đã bị XOÁ.
        /// </summary>
        internal static string _1810 {
            get {
                return ResourceManager.GetString("-1810", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy movie.
        /// </summary>
        internal static string _1993 {
            get {
                return ResourceManager.GetString("-1993", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Không tồn tại (Khách Hàng).
        /// </summary>
        internal static string _1994 {
            get {
                return ResourceManager.GetString("-1994", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Không tồn tại.
        /// </summary>
        internal static string _1995 {
            get {
                return ResourceManager.GetString("-1995", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị rating không hợp lệ.
        /// </summary>
        internal static string _1996 {
            get {
                return ResourceManager.GetString("-1996", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ điều kiện rate (Chưa xem phim/ phim chưa kết thúc).
        /// </summary>
        internal static string _1997 {
            get {
                return ResourceManager.GetString("-1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment không tồn tại hoặc đã bị XOÁ.
        /// </summary>
        internal static string _1998 {
            get {
                return ResourceManager.GetString("-1998", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đủ điều kiện comment (chưa xem hoặc phim chưa chiếu xong).
        /// </summary>
        internal static string _1999 {
            get {
                return ResourceManager.GetString("-1999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lịch chiếu kông tồn tại.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        internal static string _200 {
            get {
                return ResourceManager.GetString("200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không tìm thấy rạp chiếu phim.
        /// </summary>
        internal static string _404 {
            get {
                return ResourceManager.GetString("-404", resourceCulture);
            }
        }
    }
}
